// ============================================================================
// ACMI — Agentic Context Memory Interface: TypeScript Type Definitions
// Protocol v1.3 + Fleet Comms v1.5
// ============================================================================
// This file contains ALL TypeScript types/interfaces for ACMI.
// Pure types only — no runtime code. Includes type guards (type predicates)
// for runtime validation without dependencies.
// ============================================================================

// ---------------------------------------------------------------------------
// §1 — Key structure
// ---------------------------------------------------------------------------

/**
 * Canonical ACMI namespaces used across the fleet.
 * The protocol accepts any `[a-z][a-z0-9_-]*` string, but the fleet
 * conventions enforce these seven for cross-agent coordination.
 */
export type AcmiNamespace =
  | 'agent'     // Autonomous LLM-backed or scripted agents
  | 'user'      // Human team members (actor_type: "human")
  | 'thread'    // Cross-fleet coordination channels (append-only)
  | 'work'      // Cross-session projects, tasks, ideas
  | 'project'   // Long-running deliverables (broader than work)
  | 'session'   // Per-session ephemera (auto-generated by acmi_spawn)
  | 'registry'  // Cross-cutting metadata (fleet directory, policy, brand)
  | 'hitl'      // Human-in-the-loop queues
  | (string & {}); // Extensible — allows custom namespaces

/**
 * The three data slots every ACMI entity has.
 */
export type AcmiSlot = 'profile' | 'signals' | 'timeline';

/**
 * Full Redis key: `acmi:<namespace>:<id>:<slot>`
 */
export type AcmiKey = `acmi:${AcmiNamespace}:${string}:${AcmiSlot}`;

/**
 * Tenant-scoped key prefix (v1.3 multi-tenant).
 * `acmi:tenant:<tenant_id>:<namespace>:<id>:<slot>`
 */
export type AcmiTenantKey = `acmi:tenant:${string}:${AcmiNamespace}:${string}:${AcmiSlot}`;

/** Valid actor types per SPEC §11 — Multi-actor */
export type AcmiActorType = 'agent' | 'human' | 'system' | 'external';

/** Valid HITL statuses */
export type AcmiHitlStatus = 'open' | 'closed';

/** Role an agent can have in a thread */
export type AcmiThreadRole = 'participant' | 'lead';

/** Work item status ladder */
export type AcmiWorkStatus =
  | 'DRAFT'
  | 'RATIFIED'
  | 'IN_PROGRESS'
  | 'SHIPPED'
  | 'CANCELLED';

/** Work item priority */
export type AcmiWorkPriority = 'P0' | 'P1' | 'P2' | 'P3';

/** Speaker type for distinguishing agent reasoning from human input (v1.3) */
export type AcmiSpeakerType = 'agent' | 'human' | 'system';

// ---------------------------------------------------------------------------
// §2 — Profile
// ---------------------------------------------------------------------------

/**
 * ACMI Profile — the "who" slot.
 *
 * Stores identity metadata for any entity. v1.3 requires `actor_type`.
 * The `tenant_id` field enables multi-tenant isolation (SPEC §12).
 * Additional arbitrary fields are allowed via the index signature.
 */
export interface AcmiProfile {
  /** Actor type (v1.3 required): 'agent', 'human', 'system', 'external' */
  actor_type: AcmiActorType;

  /** Tenant isolation key (v1.3 optional). Default: "madez" */
  tenant_id?: string;

  /** Human-readable display name */
  name?: string;

  /** Functional role within the fleet */
  role?: string;

  /** VM identifier or deployment label (MCP agents) */
  host_id?: string;

  /** Free-form portfolio string (skills, capabilities) */
  description?: string;

  /** Arbitrary additional profile fields */
  [key: string]: unknown;
}

/**
 * Profile document for registry:fleet:* entries.
 * Extends AcmiProfile with fleet-specific metadata.
 */
export interface AcmiFleetProfile extends AcmiProfile {
  /** The agent's primary role in the fleet */
  fleet_role?: string;

  /** Threads this agent is typically active in */
  primary_threads?: string[];

  /** Skill tags for capability discovery */
  skills?: string[];

  /** UTC wake window, e.g. "00:00-23:59" */
  wake_window_utc?: string;

  /** The agent's primary entity ID (mirrors the key's id) */
  primary_id?: string;
}

// ---------------------------------------------------------------------------
// §3 — Signals
// ---------------------------------------------------------------------------

/**
 * ACMI Signals — the "now" slot.
 *
 * A mutable KV map of JSON values representing current state.
 * Every key is a string (1–128 chars); values are arbitrary JSON.
 */
export interface AcmiSignals {
  [key: string]: unknown;
}

/**
 * Typed signal accessor helper.
 * Use `getSignal<T>(signals, key, fallback?)` to read a typed value.
 */
export type SignalValue<T = unknown> = T | undefined;

// ---------------------------------------------------------------------------
// §4 — Timeline Events
// ---------------------------------------------------------------------------

/**
 * ACMI Timeline Event (Comms v1.5 envelope).
 *
 * The core data structure — a timestamped, correlated event that forms
 * the append-only history of an entity.
 *
 * Required fields (Comms v1.1):
 *   ts, source, kind, correlationId, summary
 *
 * v1.5 additions:
 *   parentCorrelationId, payload (typed), tags, speaker_type
 */
export interface AcmiEvent {
  /** Wall-clock ms. Monotonicity NOT required across writers. */
  ts: number;

  /**
   * Who wrote the event. Entity-ID format: `"agent:<id>"`, `"user:<id>"`.
   * Examples: "agent:claude-engineer", "user:mikey"
   */
  source: string;

  /**
   * Event taxonomy — a verb describing what happened.
   * Fleet convention uses kebab-case: "milestone-shipped", "handoff-ack", etc.
   */
  kind: string;

  /**
   * Chain identifier. Format: `<descriptiveCamelCase>-<msEpoch>`.
   * Enables tracing across entities and sessions.
   */
  correlationId: string;

  /**
   * Human-readable one-line summary, ≤500 chars.
   * Fleet convention: `[<kind-tag> @<recipient> ...] <description>`
   */
  summary: string;

  /**
   * Links this event to a parent correlationId, forming a chain.
   * The parent event may exist on a different entity's timeline.
   */
  parentCorrelationId?: string;

  /**
   * Arbitrary structured payload. SDK round-trips losslessly.
   * Common conventions: `logAssessment` (0-100 RL score), `thought`, `entryId`
   */
  payload?: AcmiEventPayload;

  /** Free-form string tags for filtering and categorization */
  tags?: string[];

  /**
   * v1.3 — distinguishes synthesizable agent reasoning from
   * lived-experience human input. May become REQUIRED in v1.4.
   */
  speaker_type?: AcmiSpeakerType;

  /** Arbitrary additional fields — adapters round-trip losslessly */
  [key: string]: unknown;
}

/**
 * Typed payload for ACMI events.
 * Extends Record<string, unknown> to allow arbitrary keys while providing
 * known field autocompletion.
 */
export interface AcmiEventPayload extends Record<string, unknown> {
  /** RL self-assessment score (0-100). Convention for *-completed / *-shipped events */
  logAssessment?: number;

  /** Free-text rubric documenting the logAssessment */
  rubric?: string;

  /** Entry ID (journal-specific convention) */
  entryId?: string;

  /** Embedded thought text */
  thought?: string;
}

/**
 * Event selection/query options for timeline reads.
 */
export interface AcmiTimelineOptions {
  /** Maximum number of events to return */
  limit?: number;

  /** Reverse chronological order (default: true) */
  reverse?: boolean;

  /** Only events with ts >= sinceMs */
  since?: number;

  /** Only events with ts <= untilMs */
  until?: number;
}

/** Sorting direction for timeline queries */
export type AcmiSortDirection = 'asc' | 'desc';

/** Field to sort timeline events by */
export type AcmiSortField = 'ts' | 'kind' | 'source';

/** Sort specification */
export interface AcmiSortSpec {
  field: AcmiSortField;
  direction: AcmiSortDirection;
}

/** Filter specification for timeline queries */
export interface AcmiEventFilter {
  /** Filter by exact kind match */
  kinds?: string[];
  /** Filter by source prefix (e.g., "agent:claude-engineer") */
  sources?: string[];
  /** Filter by correlationId prefix */
  correlationIdPrefix?: string;
  /** Filter by tag (event must have at least one matching tag) */
  tags?: string[];
  /** Filter by speaker_type */
  speakerTypes?: AcmiSpeakerType[];
}

// ---------------------------------------------------------------------------
// §5 — Fleet Comms enums (v1.5 event kinds)
// ---------------------------------------------------------------------------

/**
 * Standard event kinds used across the fleet.
 * Not exhaustive — agents may define custom kinds, but these are the
 * canonical verbs from the namespace guide.
 */
export const AcmiEventKinds = {
  /** A choice was made (often by a human via HITL) */
  DECISION: 'decision',
  /** One actor handed work to another */
  TASK_DELEGATION: 'task-delegation',
  /** The receiver of a delegation acknowledged ownership */
  HANDOFF_ACK: 'handoff-ack',
  /** A discrete deliverable is done */
  MILESTONE_SHIPPED: 'milestone-shipped',
  /** Work item lifecycle */
  WORK_CREATED: 'work-created',
  WORK_UPDATE: 'work-update',
  WORK_COMPLETED: 'work-completed',
  WORK_RATIFIED: 'work-ratified',
  /** Operational incident chain */
  INCIDENT_OPENED: 'incident-opened',
  INCIDENT_UPDATE: 'incident-update',
  INCIDENT_RESOLVED: 'incident-resolved',
  /** A scoping or prioritization call */
  SCOPE_DECISION: 'scope-decision',
  /** Lightweight cross-agent visibility note */
  COORD_NOTE: 'coord-note',
  /** Liveness signal */
  HEARTBEAT: 'heartbeat',
  /** A file/URL was shipped to a known location */
  ARTIFACT_PUBLISHED: 'artifact-published',
  /** Periodic broadcast to multiple recipients */
  TEAM_LOOP: 'team-loop',
  /** A deprecated entity path was migrated */
  NAMESPACE_ARCHIVED: 'namespace-archived',
  /** Human-in-the-loop queue events */
  HITL_REQUIRED: 'hitl-required',
  HITL_RESOLVED: 'hitl-resolved',
  /** Journal entry (Folana's Journal convention) */
  JOURNAL_ENTRY: 'journal_entry',
  /** Session lifecycle */
  SPAWN: 'spawn',
} as const;

export type AcmiEventKind = (typeof AcmiEventKinds)[keyof typeof AcmiEventKinds];

/**
 * Fleet tag conventions.
 */
export const AcmiTags = {
  /** Human-in-the-loop required */
  HITL: 'hitl',
  /** P0 priority incident */
  P0: 'p0',
  /** Production event */
  PRODUCTION: 'production',
  /** Test event */
  TEST: 'test',
  /** Automated event (no human involved) */
  AUTOMATED: 'automated',
  /** Cross-agent coordination */
  COORDINATION: 'coordination',
} as const;

export type AcmiTag = (typeof AcmiTags)[keyof typeof AcmiTags];

// ---------------------------------------------------------------------------
// §6 — CorrelationId chain types
// ---------------------------------------------------------------------------

/**
 * CorrelationId format: `<descriptiveCamelCase>-<msEpoch>`
 * e.g., "claudeEngineerSmitheryQualityWin-1778174324664"
 */
export type AcmiCorrelationId = `${string}-${number}`;

/**
 * A correlation chain — a sequence of events linked by correlationId
 * and parentCorrelationId, forming a directed acyclic graph.
 */
export interface AcmiCorrelationChain {
  /** The root correlationId */
  rootCorrelationId: string;
  /** All events in this chain, sorted by ts ascending */
  events: AcmiEvent[];
  /** The entity timelines these events were collected from */
  sources: string[];
}

// ---------------------------------------------------------------------------
// §7 — Entity types
// ---------------------------------------------------------------------------

/**
 * ACMI Agent entity — an autonomous LLM-backed or scripted agent.
 * The canonical entity type in the fleet.
 */
export interface AcmiAgent {
  id: string;
  profile: AcmiProfile | null;
  signals: AcmiSignals | null;
  timeline: AcmiEvent[];
}

/**
 * ACMI User entity — a human team member.
 * Uses `acmi:user:<id>:*` key prefix (not `acmi:human:<id>:*`).
 */
export interface AcmiUser {
  id: string;
  profile: AcmiProfile | null;
  signals: AcmiSignals | null;
  timeline: AcmiEvent[];
  /** Open HITL requests pending for this user */
  hitlOpen?: AcmiEvent[];
}

/**
 * ACMI Thread entity — a cross-fleet coordination channel.
 * Threads are append-only by convention; no single owner.
 */
export interface AcmiThread {
  id: string;
  profile: AcmiProfile | null;
  signals: AcmiSignals | null;
  timeline: AcmiEvent[];
  /** Agents currently active in this thread */
  activeAgents?: string[];
}

/**
 * ACMI Work Item — cross-session projects, tasks, or ideas.
 */
export interface AcmiWorkItem {
  id: string;
  profile: AcmiWorkProfile | null;
  signals: AcmiWorkSignals | null;
  timeline: AcmiEvent[];
}

// ---------------------------------------------------------------------------
// §8 — Work item types
// ---------------------------------------------------------------------------

/**
 * Profile for a work item. Describes what the work is.
 */
export interface AcmiWorkProfile {
  /** Title of the work item */
  title: string;
  /** Who owns this work (one or more entity IDs) */
  owner?: string;
  /** Current status per the work item ladder */
  status?: AcmiWorkStatus;
  /** Priority level */
  priority?: AcmiWorkPriority;
  /** List of expected deliverables */
  deliverables?: string[];
  /** Link to a parent work item, epic, or project */
  parentWorkId?: string;
  /** Brief description / scope statement */
  description?: string;
  /** Arbitrary additional fields */
  [key: string]: unknown;
}

/**
 * Signals (mutable state) for a work item.
 * Tracks progress, blockers, and dynamic metadata.
 */
export interface AcmiWorkSignals extends AcmiSignals {
  /** Current status (redundant with profile.status for convenience) */
  status?: AcmiWorkStatus;
  /** Estimated completion percentage (0-100) */
  progress_pct?: number;
  /** Blockers currently preventing progress */
  blockers?: string[];
  /** Links to related artifacts (URLs, file paths, PRs) */
  artifacts?: string[];
  /** Current session ID working on this item */
  active_session_id?: string;
  /** Timestamp of last activity */
  last_activity_ts?: number;
}

// ---------------------------------------------------------------------------
// §9 — Bootstrap response
// ---------------------------------------------------------------------------

/**
 * Bootstrap response — what an agent session receives on startup.
 * Returned by acmi_bootstrap or getEntity().
 */
export interface AcmiBootstrap {
  /** The entity's profile (may be null if never set) */
  profile: AcmiProfile | null;

  /** Current signals map (may be null if never set) */
  signals: AcmiSignals | null;

  /** Recent timeline events (usually last 10-50) */
  recentTimeline: AcmiEvent[];

  /** Cross-session rollup summary (set via acmi_rollup_set) */
  rollup?: AcmiRollup;

  /** Threads the agent is currently active in */
  activeThreads?: AcmiActiveThread[];

  /** Recent session spawn events */
  recentSpawns?: AcmiEvent[];
}

/**
 * A single active thread entry from acmi_bootstrap / acmi_active.
 */
export interface AcmiActiveThread {
  /** The thread key (e.g., "agent-coordination") */
  threadKey: string;
  /** The agent's role in this thread */
  role: AcmiThreadRole;
}

/**
 * Rollup — cross-session summary stored via acmi_rollup_set.
 */
export interface AcmiRollup {
  /** Summary of what happened in the previous session */
  session_summary?: string;
  /** Decisions made during the session */
  decisions_made?: AcmiRollupDecision[];
  /** Open blockers preventing progress */
  open_blockers?: string[];
  /** Priorities for the next session */
  next_session_priorities?: string[];
  /** Key correlationIds from the session */
  key_correlation_ids?: string[];
  /** Session duration in minutes */
  session_duration_min?: number;
  /** Arbitrary additional rollup fields */
  [key: string]: unknown;
}

/**
 * A single decision recorded in a rollup.
 */
export interface AcmiRollupDecision {
  /** Short identifier for the decision */
  id: string;
  /** Why the decision was made */
  rationale?: string;
  /** CorrelationId of the event where this was logged */
  cid?: string;
}

// ---------------------------------------------------------------------------
// §10 — Session and Spawn types
// ---------------------------------------------------------------------------

/**
 * Spawn event payload — logged via acmi_spawn when an agent starts a session.
 */
export interface AcmiSpawnPayload {
  /** Agent ID that spawned */
  agentId: string;
  /** Session ID (auto-generated if absent) */
  sessionId?: string;
  /** Model powering the session (e.g., "claude-opus-4-7") */
  modelId?: string;
}

/**
 * Session information derived from spawn events.
 */
export interface AcmiSessionInfo {
  /** Session ID */
  sessionId: string;
  /** Agent ID that created the session */
  agentId: string;
  /** When the session started (epoch ms) */
  startedAt: number;
  /** Model used */
  modelId?: string;
  /** When the session ended (epoch ms), if known */
  endedAt?: number;
}

// ---------------------------------------------------------------------------
// §11 — HITL (Human-in-the-Loop) types
// ---------------------------------------------------------------------------

/**
 * A HITL queue entry — represents a pending human decision.
 */
export interface AcmiHitlItem {
  /** CorrelationId of the HITL request event */
  correlationId: string;
  /** The human who needs to decide */
  targetUser: string;
  /** The question or decision prompt */
  summary: string;
  /** When the request was created (epoch ms) */
  createdAt: number;
  /** Optional structured payload with options */
  payload?: AcmiEventPayload;
}

/** HITL queue paths */
export interface AcmiHitlQueuePaths {
  open: AcmiKey;
  closed: AcmiKey;
}

// ---------------------------------------------------------------------------
// §12 — Cat / Multi-stream types
// ---------------------------------------------------------------------------

/**
 * Options for acmi_cat — merging timelines from multiple entities.
 */
export interface AcmiCatOptions {
  /** Time window filter (e.g., "24h", "7d", "30m") */
  since?: string;
  /** Maximum events to return per stream (default: 50) */
  limit?: number;
  /** Only events with ts >= this value (epoch ms) */
  sinceMs?: number;
  /** Remove duplicate events (same correlationId) across streams */
  deduplicate?: boolean;
}

/**
 * Result from a cat timeline merge.
 */
export interface AcmiCatResult {
  /** Merged and sorted events */
  events: AcmiEvent[];
  /** Total events across all streams (before limit) */
  total: number;
  /** Number of streams queried */
  streamsQueried: number;
}

// ---------------------------------------------------------------------------
// §13 — Namespace listing helpers
// ---------------------------------------------------------------------------

/**
 * Result from listing entity IDs in a namespace.
 */
export interface AcmiListResult {
  namespace: AcmiNamespace;
  ids: string[];
  count: number;
}

// ---------------------------------------------------------------------------
// §14 — Redis raw command types
// ---------------------------------------------------------------------------

/**
 * Options for the raw Redis command execution.
 */
export interface AcmiRawCommandOptions {
  /** Number of retries on failure */
  retries?: number;
  /** Whether to parse the result as JSON */
  parseJson?: boolean;
}

// ---------------------------------------------------------------------------
// §15 — Event helpers (type predicates)
// ---------------------------------------------------------------------------

/**
 * Type guard to check if an event matches a specific kind.
 */
export function isEventKind<T extends AcmiEvent>(
  event: T,
  kind: string
): event is T & { kind: typeof kind } {
  return event.kind === kind;
}

/**
 * Type guard to check if an event has a parent correlationId chain.
 */
export function hasParentCorrelationId(
  event: AcmiEvent
): event is AcmiEvent & { parentCorrelationId: string } {
  return typeof event.parentCorrelationId === 'string' && event.parentCorrelationId.length > 0;
}

/**
 * Type guard to check if an event has a payload.
 */
export function hasPayload(
  event: AcmiEvent
): event is AcmiEvent & { payload: AcmiEventPayload } {
  return typeof event.payload === 'object' && event.payload !== null;
}

/**
 * Type guard for checking if a value is a valid AcmiNamespace.
 */
export function isAcmiNamespace(value: unknown): value is AcmiNamespace {
  if (typeof value !== 'string') return false;
  return ['agent', 'user', 'thread', 'work', 'project', 'session', 'registry', 'hitl'].includes(value);
}

/**
 * Type guard for checking if a value is a valid AcmiSlot.
 */
export function isAcmiSlot(value: unknown): value is AcmiSlot {
  return value === 'profile' || value === 'signals' || value === 'timeline';
}

/**
 * Type guard for checking if a value is a valid AcmiWorkStatus.
 */
export function isAcmiWorkStatus(value: unknown): value is AcmiWorkStatus {
  if (typeof value !== 'string') return false;
  return ['DRAFT', 'RATIFIED', 'IN_PROGRESS', 'SHIPPED', 'CANCELLED'].includes(value);
}

/**
 * Type guard for complete AcmiEvent (all required fields present).
 */
export function isValidAcmiEvent(value: unknown): value is AcmiEvent {
  if (typeof value !== 'object' || value === null) return false;
  const e = value as Record<string, unknown>;
  return (
    typeof e.ts === 'number' &&
    typeof e.source === 'string' &&
    typeof e.kind === 'string' &&
    typeof e.correlationId === 'string' &&
    typeof e.summary === 'string'
  );
}

/**
 * Type guard for AcmiProfile.
 */
export function isValidAcmiProfile(value: unknown): value is AcmiProfile {
  if (typeof value !== 'object' || value === null) return false;
  const p = value as Record<string, unknown>;
  if (!p.actor_type) return false;
  return ['agent', 'human', 'system', 'external'].includes(p.actor_type as string);
}
